<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Generator as Faker;
class RealEstatePostsTableSeeder extends Seeder
{
    /**
     * Seed the 'real_estate_posts' table.
     *
     * @return void
     */
    public function run(Faker $faker)
    {
        $listingTypes = ['rent', 'sale'];
        $listYearBuild = [2000, 2010, 1900,1965,2024];
        $listPropertyType = ['house', 'condo','townhome', 'multi family', 'mobile', 'farm', 'land'];
        DB::table('real_estate_posts')->truncate();
        DB::table('real_estate_posts')->insert([
            [
                'title' => 'Modern 2 Bedroom Apartment',
                'description' => 'A beautiful modern apartment with city views and great amenities.',
                'price' => 200000.00,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'sqft' => 1200,
                'acre_lot' => 0.00,
                'address' => '500 Elm Street',
                'state' => 'CA',
                'city' => 'Los Angeles',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Spacious 4 Bedroom House',
                'description' => 'A large house perfect for a family, with a big backyard and pool.',
                'price' => 350000.00,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'sqft' => 2500,
                'acre_lot' => 0.50,
                'address' => '123 Maple Drive',
                'state' => 'TX',
                'city' => 'Austin',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Cozy 1 Bedroom Condo',
                'description' => 'A cozy condo with modern interior design, located in a quiet neighborhood.',
                'price' => 150000.00,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'sqft' => 800,
                'acre_lot' => 0.00,
                'address' => '600 Pine Ave',
                'state' => 'FL',
                'city' => 'Miami',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Charming 3 Bedroom Cottage',
                'description' => 'A charming cottage with vintage decor and a spacious yard.',
                'price' => 175000.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1600,
                'acre_lot' => 1.00,
                'address' => '456 Oak Street',
                'state' => 'NY',
                'city' => 'Albany',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Luxury 5 Bedroom Villa',
                'description' => 'A luxury villa with a private pool and breathtaking ocean views.',
                'price' => 950000.00,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'sqft' => 4500,
                'acre_lot' => 1.50,
                'address' => '777 Ocean Drive',
                'state' => 'HI',
                'city' => 'Honolulu',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Small 2 Bedroom House',
                'description' => 'A quaint house in the suburbs, perfect for a small family.',
                'price' => 180000.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'sqft' => 1200,
                'acre_lot' => 0.25,
                'address' => '789 Birch Road',
                'state' => 'GA',
                'city' => 'Atlanta',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Stylish 3 Bedroom Loft',
                'description' => 'A stylish loft in the heart of the city with modern finishes.',
                'price' => 320000.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1500,
                'acre_lot' => 0.00,
                'address' => '123 Main Street',
                'state' => 'IL',
                'city' => 'Chicago',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Beautiful 2 Bedroom Apartment',
                'description' => 'A modern apartment with a balcony and great amenities.',
                'price' => 220000.00,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'sqft' => 1000,
                'acre_lot' => 0.00,
                'address' => '201 High Street',
                'state' => 'NV',
                'city' => 'Las Vegas',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Rustic 3 Bedroom Cabin',
                'description' => 'A rustic cabin surrounded by nature, perfect for weekend getaways.',
                'price' => 250000.00,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'sqft' => 1800,
                'acre_lot' => 2.00,
                'address' => '444 Forest Lane',
                'state' => 'CO',
                'city' => 'Boulder',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Modern Studio Apartment',
                'description' => 'A sleek studio apartment with all the latest appliances.',
                'price' => 120000.00,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'sqft' => 500,
                'acre_lot' => 0.00,
                'address' => '1020 Park Avenue',
                'state' => 'NY',
                'city' => 'New York',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Charming 2 Bedroom House',
                'description' => 'A well-maintained house in a quiet suburban neighborhood.',
                'price' => 210000.00,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'sqft' => 1300,
                'acre_lot' => 0.30,
                'address' => '321 Cedar Street',
                'state' => 'NC',
                'city' => 'Charlotte',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ],
            [
                'title' => 'Grand 6 Bedroom Estate',
                'description' => 'An expansive estate with luxurious interiors and beautiful grounds.',
                'price' => 1200000.00,
                'bedrooms' => 6,
                'bathrooms' => 5,
                'sqft' => 6000,
                'acre_lot' => 5.00,
                'address' => '888 Estate Drive',
                'state' => 'CA',
                'city' => 'Beverly Hills',
                'property_type' => $faker->randomElement($listPropertyType),
                'listing_type' => $faker->randomElement($listingTypes),
                'year_built' => $faker->randomElement($listYearBuild),
                'garage' => $faker->numberBetween(0, 5) == 0 ? null : $faker->numberBetween(1, 5),
            ]
        ]);
    }
}
