<?php

return [
    'countries' => [
        [
            'id' => 1,
            'name' => 'United States',
            'states' => [
                [
                    'id' => 1,
                    'name' => 'Alabama',
                    'cities' => [
                        ['id' => 1, 'name' => 'Birmingham', 'towns' => [
                            ['id' => 1, 'name' => 'Southside'],
                            ['id' => 2, 'name' => 'Downtown'],
                            ['id' => 3, 'name' => 'Avondale'],
                            ['id' => 4, 'name' => 'Ensley'],
                            ['id' => 5, 'name' => 'Mountain Brook'],
                            ['id' => 6, 'name' => 'Five Points South'],
                            ['id' => 7, 'name' => 'Eastwood'],
                            ['id' => 8, 'name' => 'Woodlawn'],
                        ],],
                        ['id' => 2, 'name' => 'Montgomery',
                            'towns' => [
                                ['id' => 1, 'name' => 'Old Alabama Town'],
                                ['id' => 2, 'name' => 'Capitol Heights'],
                                ['id' => 3, 'name' => 'Cloverdale'],
                                ['id' => 4, 'name' => 'Woodley'],
                                ['id' => 5, 'name' => 'River Region'],
                                ['id' => 6, 'name' => 'West Montgomery'],
                            ],],
                        ['id' => 3, 'name' => 'Mobile',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Midtown'],
                                ['id' => 3, 'name' => 'North Mobile'],
                                ['id' => 4, 'name' => 'West Mobile'],
                                ['id' => 5, 'name' => 'The Loop'],
                                ['id' => 6, 'name' => 'Toulminville'],
                            ],],
                        ['id' => 4, 'name' => 'Huntsville',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Five Points'],
                                ['id' => 3, 'name' => 'Hampton Cove'],
                                ['id' => 4, 'name' => 'Medical District'],
                                ['id' => 5, 'name' => 'Providence'],
                                ['id' => 6, 'name' => 'Monrovia'],
                            ],],
                        ['id' => 5, 'name' => 'Tuscaloosa',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'University Area'],
                                ['id' => 3, 'name' => 'Northport'],
                                ['id' => 4, 'name' => 'Cottondale'],
                                ['id' => 5, 'name' => 'Berkley'],
                                ['id' => 6, 'name' => 'Alberta City'],
                            ],],
                    ],
                ],
                [
                    'id' => 2,
                    'name' => 'Alaska',
                    'cities' => [
                        [
                            'id' => 6,
                            'name' => 'Anchorage',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Spenard'],
                                ['id' => 3, 'name' => 'Midtown'],
                                ['id' => 4, 'name' => 'Hillside'],
                                ['id' => 5, 'name' => 'East Anchorage'],
                                ['id' => 6, 'name' => 'Sand Point'],
                                ['id' => 7, 'name' => 'Birchwood'],
                            ],
                        ],
                        [
                            'id' => 7,
                            'name' => 'Fairbanks',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'University'],
                                ['id' => 3, 'name' => 'North Pole'],
                                ['id' => 4, 'name' => 'South Fairbanks'],
                                ['id' => 5, 'name' => 'Chena Ridge'],
                                ['id' => 6, 'name' => 'Fox'],
                            ],
                        ],
                        [
                            'id' => 8,
                            'name' => 'Juneau',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Mendenhall Valley'],
                                ['id' => 3, 'name' => 'Douglas'],
                                ['id' => 4, 'name' => 'Auke Bay'],
                                ['id' => 5, 'name' => 'West Juneau'],
                                ['id' => 6, 'name' => 'North Juneau'],
                            ],
                        ],
                        [
                            'id' => 9,
                            'name' => 'Sitka',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Swan Lake'],
                                ['id' => 3, 'name' => 'Halibut Point'],
                                ['id' => 4, 'name' => 'Japonski Island'],
                                ['id' => 5, 'name' => 'Indian Village'],
                                ['id' => 6, 'name' => 'Baranof Island'],
                            ],
                        ],
                        [
                            'id' => 10,
                            'name' => 'Ketchikan',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Newtown'],
                                ['id' => 3, 'name' => 'South Tongass'],
                                ['id' => 4, 'name' => 'North Tongass'],
                                ['id' => 5, 'name' => 'Ward Cove'],
                                ['id' => 6, 'name' => 'Raven’s Brew'],
                            ],
                        ],
                    ],
                ],
                [
                    'id' => 3,
                    'name' => 'Arizona',
                    'cities' => [
                        [
                            'id' => 11,
                            'name' => 'Phoenix',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Phoenix'],
                                ['id' => 3, 'name' => 'South Phoenix'],
                                ['id' => 4, 'name' => 'East Phoenix'],
                                ['id' => 5, 'name' => 'West Phoenix'],
                                ['id' => 6, 'name' => 'Arcadia'],
                                ['id' => 7, 'name' => 'Desert Ridge'],
                                ['id' => 8, 'name' => 'Ahwatukee'],
                            ],
                        ],
                        [
                            'id' => 12,
                            'name' => 'Tucson',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'South Tucson'],
                                ['id' => 3, 'name' => 'East Tucson'],
                                ['id' => 4, 'name' => 'North Tucson'],
                                ['id' => 5, 'name' => 'West Tucson'],
                                ['id' => 6, 'name' => 'University Area'],
                                ['id' => 7, 'name' => 'Swan'],
                                ['id' => 8, 'name' => 'Catalina Foothills'],
                            ],
                        ],
                        [
                            'id' => 13,
                            'name' => 'Mesa',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'East Mesa'],
                                ['id' => 3, 'name' => 'West Mesa'],
                                ['id' => 4, 'name' => 'North Mesa'],
                                ['id' => 5, 'name' => 'South Mesa'],
                                ['id' => 6, 'name' => 'Mesa Grande'],
                                ['id' => 7, 'name' => 'Red Mountain'],
                                ['id' => 8, 'name' => 'Gilbert'],
                            ],
                        ],
                        [
                            'id' => 14,
                            'name' => 'Chandler',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'South Chandler'],
                                ['id' => 3, 'name' => 'North Chandler'],
                                ['id' => 4, 'name' => 'West Chandler'],
                                ['id' => 5, 'name' => 'East Chandler'],
                                ['id' => 6, 'name' => 'Ocotillo'],
                                ['id' => 7, 'name' => 'Alma School'],
                                ['id' => 8, 'name' => 'Riggs'],
                            ],
                        ],
                        [
                            'id' => 15,
                            'name' => 'Glendale',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Glendale'],
                                ['id' => 3, 'name' => 'South Glendale'],
                                ['id' => 4, 'name' => 'West Glendale'],
                                ['id' => 5, 'name' => 'East Glendale'],
                                ['id' => 6, 'name' => 'Arrowhead'],
                                ['id' => 7, 'name' => 'Peoria'],
                                ['id' => 8, 'name' => 'Mountain View'],
                            ],
                        ],
                    ],
                ],
                [
                    'id' => 4,
                    'name' => 'Arkansas',
                    'cities' => [
                        [
                            'id' => 16,
                            'name' => 'Little Rock',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Little Rock'],
                                ['id' => 3, 'name' => 'South Little Rock'],
                                ['id' => 4, 'name' => 'West Little Rock'],
                                ['id' => 5, 'name' => 'East Little Rock'],
                                ['id' => 6, 'name' => 'River Market District'],
                                ['id' => 7, 'name' => 'Midtown'],
                                ['id' => 8, 'name' => 'Hillcrest'],
                            ],
                        ],
                        [
                            'id' => 17,
                            'name' => 'Fort Smith',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Riverside'],
                                ['id' => 3, 'name' => 'West Fort Smith'],
                                ['id' => 4, 'name' => 'South Fort Smith'],
                                ['id' => 5, 'name' => 'East Fort Smith'],
                                ['id' => 6, 'name' => 'Chaffee Crossing'],
                                ['id' => 7, 'name' => 'Belle Grove'],
                                ['id' => 8, 'name' => 'Fianna Hills'],
                            ],
                        ],
                        [
                            'id' => 18,
                            'name' => 'Fayetteville',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Fayetteville'],
                                ['id' => 3, 'name' => 'South Fayetteville'],
                                ['id' => 4, 'name' => 'West Fayetteville'],
                                ['id' => 5, 'name' => 'East Fayetteville'],
                                ['id' => 6, 'name' => 'University of Arkansas Area'],
                                ['id' => 7, 'name' => 'Farmington'],
                                ['id' => 8, 'name' => 'Springdale'],
                            ],
                        ],
                        [
                            'id' => 19,
                            'name' => 'Springdale',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Springdale'],
                                ['id' => 3, 'name' => 'South Springdale'],
                                ['id' => 4, 'name' => 'West Springdale'],
                                ['id' => 5, 'name' => 'East Springdale'],
                                ['id' => 6, 'name' => 'Tontitown'],
                                ['id' => 7, 'name' => 'Bethel Heights'],
                                ['id' => 8, 'name' => 'Little Flock'],
                            ],
                        ],
                        [
                            'id' => 20,
                            'name' => 'Jonesboro',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Jonesboro'],
                                ['id' => 3, 'name' => 'South Jonesboro'],
                                ['id' => 4, 'name' => 'West Jonesboro'],
                                ['id' => 5, 'name' => 'East Jonesboro'],
                                ['id' => 6, 'name' => 'Brookland'],
                                ['id' => 7, 'name' => 'Bay'],
                                ['id' => 8, 'name' => 'Paragould'],
                            ],
                        ],
                    ],
                ],
                [
                    'id' => 5,
                    'name' => 'California',
                    'cities' => [
                        [
                            'id' => 21,
                            'name' => 'Los Angeles',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Hollywood'],
                                ['id' => 3, 'name' => 'Santa Monica'],
                                ['id' => 4, 'name' => 'Venice'],
                                ['id' => 5, 'name' => 'Westwood'],
                                ['id' => 6, 'name' => 'Koreatown'],
                                ['id' => 7, 'name' => 'Silver Lake'],
                                ['id' => 8, 'name' => 'Echo Park'],
                            ],
                        ],
                        [
                            'id' => 22,
                            'name' => 'San Francisco',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Chinatown'],
                                ['id' => 3, 'name' => 'Fisherman\'s Wharf'],
                                ['id' => 4, 'name' => 'Mission District'],
                                ['id' => 5, 'name' => 'Castro'],
                                ['id' => 6, 'name' => 'Noe Valley'],
                                ['id' => 7, 'name' => 'Haight-Ashbury'],
                                ['id' => 8, 'name' => 'North Beach'],
                            ],
                        ],
                        [
                            'id' => 23,
                            'name' => 'San Diego',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'La Jolla'],
                                ['id' => 3, 'name' => 'Gaslamp Quarter'],
                                ['id' => 4, 'name' => 'Pacific Beach'],
                                ['id' => 5, 'name' => 'Mission Beach'],
                                ['id' => 6, 'name' => 'North Park'],
                                ['id' => 7, 'name' => 'Balboa Park'],
                                ['id' => 8, 'name' => 'Clairemont'],
                            ],
                        ],
                        [
                            'id' => 24,
                            'name' => 'San Jose',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Willow Glen'],
                                ['id' => 3, 'name' => 'Almaden Valley'],
                                ['id' => 4, 'name' => 'Cambrian Park'],
                                ['id' => 5, 'name' => 'North San Jose'],
                                ['id' => 6, 'name' => 'South San Jose'],
                                ['id' => 7, 'name' => 'East San Jose'],
                                ['id' => 8, 'name' => 'West San Jose'],
                            ],
                        ],
                        [
                            'id' => 25,
                            'name' => 'Fresno',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Fresno'],
                                ['id' => 3, 'name' => 'South Fresno'],
                                ['id' => 4, 'name' => 'East Fresno'],
                                ['id' => 5, 'name' => 'West Fresno'],
                                ['id' => 6, 'name' => 'Clovis'],
                                ['id' => 7, 'name' => 'Fig Garden'],
                                ['id' => 8, 'name' => 'Madera'],
                            ],
                        ],
                    ],
                ],
                [
                    'id' => 6,
                    'name' => 'Colorado',
                    'cities' => [
                        [
                            'id' => 26,
                            'name' => 'Denver',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Capitol Hill'],
                                ['id' => 3, 'name' => 'LoDo'],
                                ['id' => 4, 'name' => 'Cherry Creek'],
                                ['id' => 5, 'name' => 'Five Points'],
                                ['id' => 6, 'name' => 'Stapleton'],
                                ['id' => 7, 'name' => 'Highlands'],
                                ['id' => 8, 'name' => 'Wash Park'],
                            ],
                        ],
                        [
                            'id' => 27,
                            'name' => 'Colorado Springs',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Old Colorado City'],
                                ['id' => 3, 'name' => 'Broadmoor'],
                                ['id' => 4, 'name' => 'Northgate'],
                                ['id' => 5, 'name' => 'East Colorado Springs'],
                                ['id' => 6, 'name' => 'Southwest Colorado Springs'],
                                ['id' => 7, 'name' => 'Mountain Shadows'],
                                ['id' => 8, 'name' => 'Powers'],
                            ],
                        ],
                        [
                            'id' => 28,
                            'name' => 'Aurora',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown Aurora'],
                                ['id' => 2, 'name' => 'South Aurora'],
                                ['id' => 3, 'name' => 'North Aurora'],
                                ['id' => 4, 'name' => 'East Aurora'],
                                ['id' => 5, 'name' => 'West Aurora'],
                                ['id' => 6, 'name' => 'Aurora Hills'],
                                ['id' => 7, 'name' => 'Sable Ridge'],
                                ['id' => 8, 'name' => 'Delmar Parkway'],
                            ],
                        ],
                        [
                            'id' => 29,
                            'name' => 'Fort Collins',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Old Town'],
                                ['id' => 3, 'name' => 'Foothills'],
                                ['id' => 4, 'name' => 'Harmony'],
                                ['id' => 5, 'name' => 'South Fort Collins'],
                                ['id' => 6, 'name' => 'West Fort Collins'],
                                ['id' => 7, 'name' => 'North Fort Collins'],
                                ['id' => 8, 'name' => 'Campus West'],
                            ],
                        ],
                        [
                            'id' => 30,
                            'name' => 'Lakewood',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Belmar'],
                                ['id' => 3, 'name' => 'Green Mountain'],
                                ['id' => 4, 'name' => 'South Lakewood'],
                                ['id' => 5, 'name' => 'North Lakewood'],
                                ['id' => 6, 'name' => 'West Lakewood'],
                                ['id' => 7, 'name' => 'East Lakewood'],
                                ['id' => 8, 'name' => 'Crown Hill'],
                            ],
                        ],
                    ],
                ],
                [
                    'id' => 7,
                    'name' => 'Connecticut',
                    'cities' => [
                        [
                            'id' => 31,
                            'name' => 'Bridgeport',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'East End'],
                                ['id' => 3, 'name' => 'South End'],
                                ['id' => 4, 'name' => 'North End'],
                                ['id' => 5, 'name' => 'West End'],
                                ['id' => 6, 'name' => 'Black Rock'],
                                ['id' => 7, 'name' => 'Hollow'],
                                ['id' => 8, 'name' => 'Park City'],
                            ],
                        ],
                        [
                            'id' => 32,
                            'name' => 'New Haven',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'Wooster Square'],
                                ['id' => 3, 'name' => 'East Rock'],
                                ['id' => 4, 'name' => 'Westville'],
                                ['id' => 5, 'name' => 'The Hill'],
                                ['id' => 6, 'name' => 'Fair Haven'],
                                ['id' => 7, 'name' => 'Newhallville'],
                                ['id' => 8, 'name' => 'Edgewood'],
                            ],
                        ],
                        [
                            'id' => 33,
                            'name' => 'Stamford',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'North Stamford'],
                                ['id' => 3, 'name' => 'South End'],
                                ['id' => 4, 'name' => 'West Side'],
                                ['id' => 5, 'name' => 'East Side'],
                                ['id' => 6, 'name' => 'Glenbrook'],
                                ['id' => 7, 'name' => 'Springdale'],
                                ['id' => 8, 'name' => 'Shippan'],
                            ],
                        ],
                        [
                            'id' => 34,
                            'name' => 'Hartford',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'West End'],
                                ['id' => 3, 'name' => 'South End'],
                                ['id' => 4, 'name' => 'North End'],
                                ['id' => 5, 'name' => 'Parkville'],
                                ['id' => 6, 'name' => 'Asylum Hill'],
                                ['id' => 7, 'name' => 'Capitol Area'],
                                ['id' => 8, 'name' => 'Clay-Arsenal'],
                            ],
                        ],
                        [
                            'id' => 35,
                            'name' => 'Waterbury',
                            'towns' => [
                                ['id' => 1, 'name' => 'Downtown'],
                                ['id' => 2, 'name' => 'South End'],
                                ['id' => 3, 'name' => 'North End'],
                                ['id' => 4, 'name' => 'East End'],
                                ['id' => 5, 'name' => 'West End'],
                                ['id' => 6, 'name' => 'Bunker Hill'],
                                ['id' => 7, 'name' => 'Chase'],
                                ['id' => 8, 'name' => 'Brookside'],
                            ],
                        ],
                    ],
                ],

                [
                    'id' => 8,
                    'name' => 'Delaware',
                    'cities' => [
                        ['id' => 36, 'name' => 'Wilmington'],
                        ['id' => 37, 'name' => 'Dover'],
                        ['id' => 38, 'name' => 'Newark'],
                        ['id' => 39, 'name' => 'Middletown'],
                        ['id' => 40, 'name' => 'Smyrna'],
                    ],
                ],
                [
                    'id' => 9,
                    'name' => 'District of Columbia',
                    'cities' => [
                        ['id' => 41, 'name' => 'Washington'],
                    ],
                ],
                [
                    'id' => 10,
                    'name' => 'Florida',
                    'cities' => [
                        ['id' => 42, 'name' => 'Jacksonville'],
                        ['id' => 43, 'name' => 'Miami'],
                        ['id' => 44, 'name' => 'Tampa'],
                        ['id' => 45, 'name' => 'Orlando'],
                        ['id' => 46, 'name' => 'St. Petersburg'],
                    ],
                ],
                [
                    'id' => 11,
                    'name' => 'Georgia',
                    'cities' => [
                        ['id' => 47, 'name' => 'Atlanta'],
                        ['id' => 48, 'name' => 'Augusta'],
                        ['id' => 49, 'name' => 'Columbus'],
                        ['id' => 50, 'name' => 'Savannah'],
                        ['id' => 51, 'name' => 'Athens'],
                    ],
                ],
                [
                    'id' => 12,
                    'name' => 'Hawaii',
                    'cities' => [
                        ['id' => 52, 'name' => 'Honolulu'],
                        ['id' => 53, 'name' => 'Hilo'],
                        ['id' => 54, 'name' => 'Kailua'],
                        ['id' => 55, 'name' => 'Kapolei'],
                        ['id' => 56, 'name' => 'Kaneohe'],
                    ],
                ],
                [
                    'id' => 13,
                    'name' => 'Idaho',
                    'cities' => [
                        ['id' => 57, 'name' => 'Boise'],
                        ['id' => 58, 'name' => 'Meridian'],
                        ['id' => 59, 'name' => 'Nampa'],
                        ['id' => 60, 'name' => 'Idaho Falls'],
                        ['id' => 61, 'name' => 'Pocatello'],
                    ],
                ],
                [
                    'id' => 14,
                    'name' => 'Illinois',
                    'cities' => [
                        ['id' => 62, 'name' => 'Chicago'],
                        ['id' => 63, 'name' => 'Aurora'],
                        ['id' => 64, 'name' => 'Naperville'],
                        ['id' => 65, 'name' => 'Joliet'],
                        ['id' => 66, 'name' => 'Rockford'],
                    ],
                ],
                [
                    'id' => 15,
                    'name' => 'Indiana',
                    'cities' => [
                        ['id' => 67, 'name' => 'Indianapolis'],
                        ['id' => 68, 'name' => 'Fort Wayne'],
                        ['id' => 69, 'name' => 'Evansville'],
                        ['id' => 70, 'name' => 'South Bend'],
                        ['id' => 71, 'name' => 'Carmel'],
                    ],
                ],
                [
                    'id' => 16,
                    'name' => 'Iowa',
                    'cities' => [
                        ['id' => 72, 'name' => 'Des Moines'],
                        ['id' => 73, 'name' => 'Cedar Rapids'],
                        ['id' => 74, 'name' => 'Davenport'],
                        ['id' => 75, 'name' => 'Sioux City'],
                        ['id' => 76, 'name' => 'Iowa City'],
                    ],
                ],
                [
                    'id' => 17,
                    'name' => 'Kansas',
                    'cities' => [
                        ['id' => 77, 'name' => 'Wichita'],
                        ['id' => 78, 'name' => 'Overland Park'],
                        ['id' => 79, 'name' => 'Kansas City'],
                        ['id' => 80, 'name' => 'Olathe'],
                        ['id' => 81, 'name' => 'Topeka'],
                    ],
                ],
                [
                    'id' => 18,
                    'name' => 'Kentucky',
                    'cities' => [
                        ['id' => 82, 'name' => 'Louisville'],
                        ['id' => 83, 'name' => 'Lexington'],
                        ['id' => 84, 'name' => 'Bowling Green'],
                        ['id' => 85, 'name' => 'Owensboro'],
                        ['id' => 86, 'name' => 'Covington'],
                    ],
                ],
                [
                    'id' => 19,
                    'name' => 'Louisiana',
                    'cities' => [
                        ['id' => 87, 'name' => 'New Orleans'],
                        ['id' => 88, 'name' => 'Baton Rouge'],
                        ['id' => 89, 'name' => 'Shreveport'],
                        ['id' => 90, 'name' => 'Lafayette'],
                        ['id' => 91, 'name' => 'Lake Charles'],
                    ],
                ],
                [
                    'id' => 20,
                    'name' => 'Maine',
                    'cities' => [
                        ['id' => 92, 'name' => 'Portland'],
                        ['id' => 93, 'name' => 'Lewiston'],
                        ['id' => 94, 'name' => 'Bangor'],
                        ['id' => 95, 'name' => 'South Portland'],
                        ['id' => 96, 'name' => 'Auburn'],
                    ],
                ],
                [
                    'id' => 21,
                    'name' => 'Maryland',
                    'cities' => [
                        ['id' => 97, 'name' => 'Baltimore'],
                        ['id' => 98, 'name' => 'Frederick'],
                        ['id' => 99, 'name' => 'Rockville'],
                        ['id' => 100, 'name' => 'Gaithersburg'],
                        ['id' => 101, 'name' => 'Bowie'],
                    ],
                ],
                [
                    'id' => 22,
                    'name' => 'Massachusetts',
                    'cities' => [
                        ['id' => 102, 'name' => 'Boston'],
                        ['id' => 103, 'name' => 'Worcester'],
                        ['id' => 104, 'name' => 'Springfield'],
                        ['id' => 105, 'name' => 'Cambridge'],
                        ['id' => 106, 'name' => 'Lowell'],
                    ],
                ],
                [
                    'id' => 23,
                    'name' => 'Michigan',
                    'cities' => [
                        ['id' => 107, 'name' => 'Detroit'],
                        ['id' => 108, 'name' => 'Grand Rapids'],
                        ['id' => 109, 'name' => 'Warren'],
                        ['id' => 110, 'name' => 'Sterling Heights'],
                        ['id' => 111, 'name' => 'Ann Arbor'],
                    ],
                ],
                [
                    'id' => 24,
                    'name' => 'Minnesota',
                    'cities' => [
                        ['id' => 112, 'name' => 'Minneapolis'],
                        ['id' => 113, 'name' => 'Saint Paul'],
                        ['id' => 114, 'name' => 'Rochester'],
                        ['id' => 115, 'name' => 'Duluth'],
                        ['id' => 116, 'name' => 'Bloomington'],
                    ],
                ],
                [
                    'id' => 25,
                    'name' => 'Mississippi',
                    'cities' => [
                        ['id' => 117, 'name' => 'Jackson'],
                        ['id' => 118, 'name' => 'Gulfport'],
                        ['id' => 119, 'name' => 'Southaven'],
                        ['id' => 120, 'name' => 'Hattiesburg'],
                        ['id' => 121, 'name' => 'Biloxi'],
                    ],
                ],
                [
                    'id' => 26,
                    'name' => 'Missouri',
                    'cities' => [
                        ['id' => 122, 'name' => 'Kansas City'],
                        ['id' => 123, 'name' => 'Saint Louis'],
                        ['id' => 124, 'name' => 'Springfield'],
                        ['id' => 125, 'name' => 'Columbia'],
                        ['id' => 126, 'name' => 'Independence'],
                    ],
                ],
                [
                    'id' => 27,
                    'name' => 'Montana',
                    'cities' => [
                        ['id' => 127, 'name' => 'Billings'],
                        ['id' => 128, 'name' => 'Missoula'],
                        ['id' => 129, 'name' => 'Great Falls'],
                        ['id' => 130, 'name' => 'Bozeman'],
                        ['id' => 131, 'name' => 'Butte'],
                    ],
                ],
                [
                    'id' => 28,
                    'name' => 'Nebraska',
                    'cities' => [
                        ['id' => 132, 'name' => 'Omaha'],
                        ['id' => 133, 'name' => 'Lincoln'],
                        ['id' => 134, 'name' => 'Bellevue'],
                        ['id' => 135, 'name' => 'Grand Island'],
                        ['id' => 136, 'name' => 'Kearney'],
                    ],
                ],
                [
                    'id' => 29,
                    'name' => 'Nevada',
                    'cities' => [
                        ['id' => 137, 'name' => 'Las Vegas'],
                        ['id' => 138, 'name' => 'Henderson'],
                        ['id' => 139, 'name' => 'Reno'],
                        ['id' => 140, 'name' => 'North Las Vegas'],
                        ['id' => 141, 'name' => 'Sparks'],
                    ],
                ],
                [
                    'id' => 30,
                    'name' => 'New Hampshire',
                    'cities' => [
                        ['id' => 142, 'name' => 'Manchester'],
                        ['id' => 143, 'name' => 'Nashua'],
                        ['id' => 144, 'name' => 'Concord'],
                        ['id' => 145, 'name' => 'Derry'],
                        ['id' => 146, 'name' => 'Dover'],
                    ],
                ],
                [
                    'id' => 31,
                    'name' => 'New Jersey',
                    'cities' => [
                        ['id' => 147, 'name' => 'Newark'],
                        ['id' => 148, 'name' => 'Jersey City'],
                        ['id' => 149, 'name' => 'Paterson'],
                        ['id' => 150, 'name' => 'Elizabeth'],
                        ['id' => 151, 'name' => 'Edison'],
                    ],
                ],
                [
                    'id' => 32,
                    'name' => 'New Mexico',
                    'cities' => [
                        ['id' => 152, 'name' => 'Albuquerque'],
                        ['id' => 153, 'name' => 'Las Cruces'],
                        ['id' => 154, 'name' => 'Rio Rancho'],
                        ['id' => 155, 'name' => 'Santa Fe'],
                        ['id' => 156, 'name' => 'Roswell'],
                    ],
                ],
                [
                    'id' => 33,
                    'name' => 'New York',
                    'cities' => [
                        ['id' => 157, 'name' => 'New York City'],
                        ['id' => 158, 'name' => 'Buffalo'],
                        ['id' => 159, 'name' => 'Rochester'],
                        ['id' => 160, 'name' => 'Yonkers'],
                        ['id' => 161, 'name' => 'Syracuse'],
                    ],
                ],
                [
                    'id' => 34,
                    'name' => 'North Carolina',
                    'cities' => [
                        ['id' => 162, 'name' => 'Charlotte'],
                        ['id' => 163, 'name' => 'Raleigh'],
                        ['id' => 164, 'name' => 'Greensboro'],
                        ['id' => 165, 'name' => 'Durham'],
                        ['id' => 166, 'name' => 'Winston-Salem'],
                    ],
                ],
                [
                    'id' => 35,
                    'name' => 'North Dakota',
                    'cities' => [
                        ['id' => 167, 'name' => 'Fargo'],
                        ['id' => 168, 'name' => 'Bismarck'],
                        ['id' => 169, 'name' => 'Grand Forks'],
                        ['id' => 170, 'name' => 'Minot'],
                        ['id' => 171, 'name' => 'West Fargo'],
                    ],
                ],
                [
                    'id' => 36,
                    'name' => 'Ohio',
                    'cities' => [
                        ['id' => 172, 'name' => 'Columbus'],
                        ['id' => 173, 'name' => 'Cleveland'],
                        ['id' => 174, 'name' => 'Cincinnati'],
                        ['id' => 175, 'name' => 'Toledo'],
                        ['id' => 176, 'name' => 'Akron'],
                    ],
                ],
                [
                    'id' => 37,
                    'name' => 'Oklahoma',
                    'cities' => [
                        ['id' => 177, 'name' => 'Oklahoma City'],
                        ['id' => 178, 'name' => 'Tulsa'],
                        ['id' => 179, 'name' => 'Norman'],
                        ['id' => 180, 'name' => 'Broken Arrow'],
                        ['id' => 181, 'name' => 'Edmond'],
                    ],
                ],
                [
                    'id' => 38,
                    'name' => 'Oregon',
                    'cities' => [
                        ['id' => 182, 'name' => 'Portland'],
                        ['id' => 183, 'name' => 'Salem'],
                        ['id' => 184, 'name' => 'Eugene'],
                        ['id' => 185, 'name' => 'Gresham'],
                        ['id' => 186, 'name' => 'Hillsboro'],
                    ],
                ],
                [
                    'id' => 39,
                    'name' => 'Pennsylvania',
                    'cities' => [
                        ['id' => 187, 'name' => 'Philadelphia'],
                        ['id' => 188, 'name' => 'Pittsburgh'],
                        ['id' => 189, 'name' => 'Allentown'],
                        ['id' => 190, 'name' => 'Erie'],
                        ['id' => 191, 'name' => 'Reading'],
                    ],
                ],
                [
                    'id' => 40,
                    'name' => 'Rhode Island',
                    'cities' => [
                        ['id' => 192, 'name' => 'Providence'],
                        ['id' => 193, 'name' => 'Cranston'],
                        ['id' => 194, 'name' => 'Warwick'],
                        ['id' => 195, 'name' => 'Pawtucket'],
                        ['id' => 196, 'name' => 'East Providence'],
                    ],
                ],
                [
                    'id' => 41,
                    'name' => 'South Carolina',
                    'cities' => [
                        ['id' => 197, 'name' => 'Columbia'],
                        ['id' => 198, 'name' => 'Charleston'],
                        ['id' => 199, 'name' => 'North Charleston'],
                        ['id' => 200, 'name' => 'Mount Pleasant'],
                        ['id' => 201, 'name' => 'Rock Hill'],
                    ],
                ],
                [
                    'id' => 42,
                    'name' => 'South Dakota',
                    'cities' => [
                        ['id' => 202, 'name' => 'Sioux Falls'],
                        ['id' => 203, 'name' => 'Rapid City'],
                        ['id' => 204, 'name' => 'Aberdeen'],
                        ['id' => 205, 'name' => 'Brookings'],
                        ['id' => 206, 'name' => 'Watertown'],
                    ],
                ],
                [
                    'id' => 43,
                    'name' => 'Tennessee',
                    'cities' => [
                        ['id' => 207, 'name' => 'Nashville'],
                        ['id' => 208, 'name' => 'Memphis'],
                        ['id' => 209, 'name' => 'Knoxville'],
                        ['id' => 210, 'name' => 'Chattanooga'],
                        ['id' => 211, 'name' => 'Clarksville'],
                    ],
                ],
                [
                    'id' => 44,
                    'name' => 'Texas',
                    'cities' => [
                        ['id' => 212, 'name' => 'Houston'],
                        ['id' => 213, 'name' => 'San Antonio'],
                        ['id' => 214, 'name' => 'Dallas'],
                        ['id' => 215, 'name' => 'Austin'],
                        ['id' => 216, 'name' => 'Fort Worth'],
                    ],
                ],
                [
                    'id' => 45,
                    'name' => 'Utah',
                    'cities' => [
                        ['id' => 217, 'name' => 'Salt Lake City'],
                        ['id' => 218, 'name' => 'West Valley City'],
                        ['id' => 219, 'name' => 'Provo'],
                        ['id' => 220, 'name' => 'West Jordan'],
                        ['id' => 221, 'name' => 'Orem'],
                    ],
                ],
                [
                    'id' => 46,
                    'name' => 'Vermont',
                    'cities' => [
                        ['id' => 222, 'name' => 'Burlington'],
                        ['id' => 223, 'name' => 'South Burlington'],
                        ['id' => 224, 'name' => 'Rutland'],
                        ['id' => 225, 'name' => 'Barre'],
                        ['id' => 226, 'name' => 'Montpelier'],
                    ],
                ],
                [
                    'id' => 47,
                    'name' => 'Virginia',
                    'cities' => [
                        ['id' => 227, 'name' => 'Virginia Beach'],
                        ['id' => 228, 'name' => 'Norfolk'],
                        ['id' => 229, 'name' => 'Chesapeake'],
                        ['id' => 230, 'name' => 'Arlington'],
                        ['id' => 231, 'name' => 'Richmond'],
                    ],
                ],
                [
                    'id' => 48,
                    'name' => 'Washington',
                    'cities' => [
                        ['id' => 232, 'name' => 'Seattle'],
                        ['id' => 233, 'name' => 'Spokane'],
                        ['id' => 234, 'name' => 'Tacoma'],
                        ['id' => 235, 'name' => 'Vancouver'],
                        ['id' => 236, 'name' => 'Bellevue'],
                    ],
                ],
                [
                    'id' => 49,
                    'name' => 'West Virginia',
                    'cities' => [
                        ['id' => 237, 'name' => 'Charleston'],
                        ['id' => 238, 'name' => 'Huntington'],
                        ['id' => 239, 'name' => 'Morgantown'],
                        ['id' => 240, 'name' => 'Parkersburg'],
                        ['id' => 241, 'name' => 'Wheeling'],
                    ],
                ],
                [
                    'id' => 50,
                    'name' => 'Wisconsin',
                    'cities' => [
                        ['id' => 242, 'name' => 'Milwaukee'],
                        ['id' => 243, 'name' => 'Madison'],
                        ['id' => 244, 'name' => 'Green Bay'],
                        ['id' => 245, 'name' => 'Kenosha'],
                        ['id' => 246, 'name' => 'Racine'],
                    ],
                ],
                [
                    'id' => 51,
                    'name' => 'Wyoming',
                    'cities' => [
                        ['id' => 247, 'name' => 'Cheyenne'],
                        ['id' => 248, 'name' => 'Casper'],
                        ['id' => 249, 'name' => 'Laramie'],
                        ['id' => 250, 'name' => 'Gillette'],
                        ['id' => 251, 'name' => 'Rock Springs'],
                    ],
                ],
            ],
        ]
    ],
];
