<?php
return [
    "Abbeville",
    "Abbeville",
    "Abbot",
    "Aberdeen",
    "Aberdeen",
    "Abilene",
    "Abington",
    "Abington",
    "Abiquiu",
    "Accokeek",
    "Acton",
    "Acton",
    "Acushnet",
    "Acworth",
    "Ada",
    "Ada",
    "Adairsville",
    "Adairville",
    "Adams",
    "Adams",
    "Adamsburg",
    "Ada Township",
    "Addison",
    "Addison",
    "Adel",
    "Adel",
    "Adelanto",
    "Adelphi",
    "Adjuntas",
    "Adrian",
    "Advance",
    "Afton",
    "Agawam",
    "Agoura Hills",
    "Aguada",
    "Aguadilla",
    "Aguas Buenas",
    "Aibonito",
    "Aiken",
    "Ainaloa CDP",
    "Ainsworth",
    "Airway Heights",
    "Aitkin",
    "Ajo",
    "Akron",
    "Alabaster",
    "Alachua",
    "Alameda",
    "Alamo",
    "Alamo",
    "Albany",
    "Albany",
    "Albany",
    "Albany",
    "Albemarle",
    "Albert Lea",
    "Albertville",
    "Albia",
    "Albin",
    "Albion",
    "Albion",
    "Albion",
    "Alderwood Manor",
    "Aldine",
    "Aledo",
    "Alexander",
    "Alexander City",
    "Alexandria",
    "Alexandria",
    "Alexandria",
    "Alford",
    "Alfred",
    "Algoma",
    "Algona",
    "Algonquin",
    "Alhambra",
    "Alice",
    "Aliquippa",
    "Aliso Viejo",
    "Allagash",
 "Allen",
    "Allendale",
    "Allen Park",
    "Alliance",
    "Alliance",
    "Allison",
    "Allouez",
    "Alma",
    "Alma",
    "Alma",
    "Alma",
    "Alna",
    "Alpena",
    "Alpha Base Camp",
    "Alpharetta",
    "Alpine",
    "Alpine",
    "Alpine",
    "Alpine",
    "Alpine Township",
    "Alsip",
    "Altadena",
    "Alton",
    "Alton",
    "Alton",
    "Altona",
    "Altoona",
    "Altus",
    "Alvin",
    "Alys Beach",
    "Amboy",
    "American Canyon",
    "American Fork",
    "Americus",
    "Amherst",
    "Amherst",
    "Amherst",
    "Amherst",
    "Amity",
    "Amity",
    "Ammon",
    "Anaconda",
    "Anacortes",
    "Anamosa",
    "Añasco",
    "Andalusia",
    "Anderson",
    "Anderson",
    "Andover",
    "Andover",
    "Andover",
    "Andover",
    "Andrews",
    "Andrews",
    "Angels Camp",
    "Angleton",
    "Angola",
    "Ankeny",
    "Anna",
    "Annandale",

    "Annville",
    "Anoka",
    "Anson",
    "Anson",
    "Anthony",
    "Anthony",
    "Antigo",
    "Antioch",
    "Antlers",
    "Antonito",
    "Apache Junction",
    "Apalachicola",
    "Apex",
    "Appleton",
    "Apple Valley",
    "Apple Valley",
    "Aptos",
    "Aragon",
    "Aransas Pass",
    "Arapahoe",
    'Arbutus',
    'Arcadia',
    'Arcata',
    'Archbold',
    'Archdale',
    'Arden Hills',
    'Ardmore',
    'Ardmore',
    'Ardmore',
    'Argos',
    'Arkadelphia',
    'Arkansas City',
    'Arkoma',
    'Arkoma',
    'Arlington',
    'Arlington',
    'Arlington Heights',
    'Arma',
    'Armour',
    'Arnold',

    "Arnold",
    "Arona",
    "Arrowsic",
    "Arroyo",
    "Arroyo Grande",
    "Artesia",
    "Artesia",
    "Arundel",
    "Arvada",
    "Arvin",
    "Asbury",
    "Asbury Park",
    "Ashburn",
    "Ashburnham",
    "Ashby",
    "Ashdown",
    "Asheboro",
    "Asherton",
    "Ashfield",
    "Ashford",
    "Ash Grove",
    "Ashland",
    "Ashland",
    "Ashland",
    "Ashland",
    "Ashland",
    "Ashland",
    "Ashland",
    "Ashland",
    "Ashley",
    "Ashwaubenon",
    "Askov",
    "Aspen",
    "Aspen Hill",
    "Aspen Park",
    "Astoria",
    "Atascadero",
    "Atascocita",
    "Atchison",
    "Athens",
    "Athens",
    "Athens",
    "Athens",
    "Athens",
    "Atherton",
    "Athol",
    "Atkinson",
    "Atlanta",
    "Atlanta",
    "Atlantic",
    "Atlantic Beach",
    "Atoka",
    "Attalla",
    "Attica",
    "Atwater",
    "Atwood",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn",
    "Auburn Hills",
    "Audubon",
    "Augusta",
    "Aurora",
    "Aurora",
    "Aurora",
    "Aurora",
    "Aurora",
    "Aurora",
    "Aurora",
    "Austin",
    "Austintown",
    "Au Train", "Bainbridge",
    "Bainbridge",
    "Bainbridge Island",
    "Bairoil",
    "Baker",
    "Baker",
    "Baker",
    "Baker City",
    "Bakersville",
    "Balch Springs",
    "Baldwin",
    "Baldwin",
    "Baldwin Park",
    "Ballenger Creek",
    "Ballinger",
    "Ballwin",
    "Bamberg",
    "Bandera",
    "Bangor",
    "Banner Elk",
    "Banning",
    "Baraboo",
    "Barberton",
    "Barbourville",
    "Barceloneta",
    "Bardstown",
    "Bar Harbor",
    "Barkhamsted",
    "Barnegat Township",
    "Barnsdall",
    "Barnstable",
    "Barnum",
    "Bar Nunn",
    "Barnwell",
    "Barranquitas",
    'Barre',
    'Barrington',
    'Barstow',
    "Bartlett",
    "Bartlett",
    "Bartlett",
    "Basecamp F",
    "Basin",
    "Bassett",
    "Bastrop",
    "Bastrop",
    "Batavia",
    "Batavia",
    "Batavia",
    "Batesville",
    "Batesville",
    "Bath",
    "Bath",
    "Bath",
    "Battle Creek",
    "Battle Ground",
    "Battle Mountain",
    "Baudette",

    "Bayamón",
    "Bayard",
    "Bay City",
    "Bay City",
    "Bayfield",
    "Bayonet Point",
    "Bayonne",
    "Bayou La Batre",
    "Bay Point",
    "Bay Saint Louis",
    "Baytown",
    "Bay Village",
    "Bayville",
    "Beach",
    "Beach City",
    "Beach Haven",
    "Beach Park",
    "Beachwood",
    "Beachwood",
    "Beacon",
    "Beacon Falls",
    "Beals",
    "Bean Station",
    "Bear River",
    "Beattyville",
    "Beaufort",
    "Beaufort",
    "Beaumont",
    "Beaver",
    "Beaver",
    "Beaver",
    "Beaver City",
    "Beaver Cove",
    "Beavercreek",
    "Beaver Dam",
    "Becker",
    "Becket",
    "Beckley",
    "Beclabito",
    "Beddington",
    "Bedford",
    "Bedford",
    "Bedford",
    "Bedford",
    "Bedford",
    "Bedford",
    "Bedford",
    "Bedford",
    "Bedford Heights",
    "Beech Grove",
    "Beekman",
    "Beeville",
    "Bel Air",
    "Bel Aire",
    "Belchertown",
    "Belcourt",
    "Belen",
    "Belfast",
    "Belfield",
    "Belgrade",
    "Belgrade",
    "Belhaven",
    "Bell",
    "Bellaire",
    "Bellefontaine",
    "Bellefontaine Neighbors",
    "Bellefonte",
    "Belle Fourche",
    "Belle Glade",
    "Belleville",
    "Bellevue",
    "Bellflower",
    "Bell Gardens",
    "Bellingham",
    "Bellmawr",
    "Bellows Falls",
    "Bellville",
    "Bellwood",
    "Belmond",
    "Belmont",
    "Beloit",
    "Belpre",
    "Belton",
    "Beltsville",
    "Belvedere Park",
    "Belvidere",
    "Bend",
    "Bennettsville",
    "Bennington",
    "Benton",
    "Benton Harbor",
    "Bentonville",
    "Benzonia",
    "Berlin",
    "Berlin",
    "Berlin",
    "Berlin",
    "Berrien Springs",
    "Berryville",
    "Bessemer",
    "Bessemer City",
    "Bethalto",
    "Bethlehem",
    "Bethlehem",
    "Betsy Layne",
    "Beulah",
    "Beverly",
    "Beverly Hills",
    "Beverly Shores",
    "Beverly Woods",
    "Big Pine",
    "Big Rapids",
    "Big Spring",
    "Big Stone Gap",
    "Billings",
    "Binghamton",
    "Birmingham",
    "Birnamwood",
    "Bristol",
    "Bristol",
    "Bristol",
    "Bristol",
    "Bristol",
    "Bristol",
    "Bristol",
    "Bristol",
    "British Columbia",
    "Broadway",
    "Broken Arrow",
    "Bronson",
    "Brooklyn",
    "Brooklyn",
    "Brooklyn",
    "Brookline",
    "Brookport",
    "Broomfield",
    "Brownsburg",
    "Brownsville",
    "Brownsville",
    "Bruce",
    "Bryan",
    "Bryant",
    "Bryson City",
    "Buckhannon",
    "Bucyrus",
    "Buford",
    "Buhl",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burlington",
    "Burnsville",
    "Burr Ridge",
    "Burton",
    "Burtonsville",
    "Bushnell",
    "Butler",
    "Butler",
    "Butler",
    "Butler",
    "Butler",
    "Byron",
    "Cabot",
    "Cabo Rojo",
    "Cadillac",
    "Cairo",
    "Calabasas",
    "Calais",
    "California",
    "California",
    "California",
    "California",
    "California",
    "California",
    "Calimesa",
    "Calumet City",
    "Calumet Park",
    "Camas",
    "Camp Hill",
    "Campbell",
    "Campbellsville",
    "Candler",
    "Canfield",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Canton",
    "Cape Girardeau",
    "Cape May",
    "Cape May Court House",
    "Capitol Heights",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Carbondale",
    "Cardiff",
    "Carlsbad",
    "Carlisle",
    "Carlisle",
    "Carlisle",
    "Carrollton",
    "Carson City",
    "Cartersville",
    "Carthage",
    "Carthage",
    "Carthage",
    "Carthage",
    "Cary",
    "Casper",
    "Castro Valley",
    "Catonsville",
    "Cedar Hill",
    "Cedar Park",
    "Cedar Rapids",
    "Cedarburg",
    "Celina",
    "Center",
    "Center City",
    "Central",
    "Central City",
    "Central Falls",
    "Central Point",
    "Central Square",
    "Centreville",
    "Chalmette",
    "Chambersburg",
    "Champaign",
    "Chandler",
    "Chandler",
    "Chandler",
    "Chandler",
    "Chandler",
    "Channahon",
    "Chapel Hill",
    "Charleston",
    "Charleston",
    "Charleston",
    "Charleston",
    "Charleston",
    "Charlestown",
    "Charlotte",
    "Charlotte",
    "Charlotte",
    "Charlotte",
    "Charlotte",
    "Charlottesville",
    "Chaska",
    "Chattanooga",
    "Cheektowaga",
    "Cheyenne",
    "Chico",
    "Chicopee",
    "China Grove",
    "Chippewa Lake",
    "Chippewa Falls",
    "Chittenango",
    "Chocowinity",
    "Chula Vista",
    "Cicero",
    "Cincinnati",
    "Berlin",
    "Berlin",
    "Bernalillo",
    "Bernardston",
    "Bernards Township",
    "Berthoud",
    "Bertram",
    "Berwick",
    "Berwick",
    "Berwick",
    "Berwyn",
    "Bessemer",
    "Bessemer City",
    "Bethalto",
    "Bethany",
    "Bethany",
    "Bethany",
    "Bethany Beach",
    "Bethel",
    "Bethel",
    "Bethel",
    "Bethel",
    "Bethel Park",
    "Bethlehem",
    "Bettendorf",
    "Beverly",
    "Beverly Hills",
    "Beverly Hills",
    "Bexley",
    "Big Bear City",
    "Big Bear Lake",
    "Big Lake",
    "Big Lake",
    "Big Piney",
    "Big Rapids",
    "Big Sandy",
    "Big Sky",
    "Big Spring",
    "Big Timber",
    "Billerica",
    "Bingham",
    "Birmingham",
    "Bisbee",
    "Bishop",
    "Bishopville",
    "Bismarck",
    "Bison",
    "Bixby",
    "Blackfoot",
    "Blacksburg",
    "Blackstone",
    "Bladensburg",
    "Blaine",
    "Blaine",
    "Blair",
    "Bloomfield",
    "Bloomfield",
    "Bloomfield",
    "Bloomfield",
    "Bloomingdale",
    "Blooming Grove",
    "Bloomington",
    "Bloomsburg",
    "Blountstown",
    "Blowing Rock",
    "Blue Ash",
    "Blue Earth",
    "Bluefield",
    "Blue Hill",
    "Blue Island",
    "Blue Springs",
    "Bluffton",
    "Blythe",
    "Blytheville",
    "Boardman",
    "Bock",
    "Boerne",
    "Bogalusa",
    "Boise City",
    "Bolingbrook",
    "Bolivar",
    "Bolivar",
    "Bolton",
    "Bolton",
    "Bon Air",
    "Bonaire",
    "Bonham",
    "Bonita Springs",
    "Bonners Ferry",
    "Bonne Terre",
    "Bonney Lake",
    'Bock',
    'Boerne',
    'Bogalusa',
    'Boise City',
    'Bolingbrook',
    'Bolivar',
    'Bolivar',
    'Bolton',
    'Bolton',
    'Bon Air',
    'Bonaire',
    'Bonham',
    'Bonita Springs',
    'Bonners Ferry',
    'Bonne Terre',
    'Bonney Lake',
    'Boone',
    'Boonville',
    'Boonville',
    'Boonville',
    'Boothbay',
    'Boothbay Harbor',
    'Borger',
    'Bothell',
    'Boulder',
    'Boulder Creek',
    'Bound Brook',
    'Bountiful',
    'Bourbonnais',
    'Bourne',
    'Bowbells',
    'Bowdoin',
    'Bowdoinham',
    'Bowerbank',
    'Bowie',
    'Bowling Green',
    'Bowling Green',
    'Bowling Green',
    'Bowman',
    'Boxborough',
    "Boydton",
    "Boylston",
    "Boylston",
    "Bozrah",
    "Brackettville",
    "Bradford",
    "Bradley",
    "Bradley",
    "Brady",
    "Braham",
    "Brainerd",
    "Braintree",
    "Brandon",
    "Brandon",
    "Brandon",
    "Branford",
    "Branson",
    "Braselton",
    "Brattleboro",
    "Bravo Base Camp",




];



